"""empty message

Revision ID: b3debdcfa7d2
Revises: e08cf2051b6d
Create Date: 2022-12-23 10:37:13.945974

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = 'b3debdcfa7d2'
down_revision = 'e08cf2051b6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('userId', sa.Integer()))
    op.create_foreign_key(None, 'teams', 'users', ['userId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'userId')
    # ### end Alembic commands ###
